# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: git://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: golangci-lint
        stages:
          - commit
      - id: go-test-mod
        stages:
          - push
