# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: git://github.com/Bahjat/pre-commit-golang
    rev: master
    hooks:
      - id: golangci-lint
        stages:
          - commit
      - id: go-unit-tests
        stages:
          - push
